### ISSUE TITLE
Physical Components with nature Behaviour are drawn yellow

### ISSUE THREAD

**Issue by malnemark** [DSD-DBS/capellambse-context-diagrams#22]
Hi all,
I realised that on physical architecture level the components are not having the expected color: 
Node: Yellow
Behaviour: Blue (like logical components)

**Comment by ewuerger** [comment]
Hi malnemark,

thank you for reporting this bug. I think the styling that you want is the standard style displayed in the Capella diagram editor. Therefore this should be implemented in py-capellambse instead of *fixed* by the custom style feature in this extension. I created an issue for you in the repo of the main project. Please watch the linked new issue for updates.
